apiVersion: v1
appVersion: v1.0.0

description: did-management-service deployment

name: did-management-service

version: 1.0.10

dependencies:
  - name: library
    version: 1.0.0
    repository: "https://gitlab.com/api/v4/projects/40471958/packages/helm/stable/"
